# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Clone and publish darkan-core
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        owner: titandino/darkan-core
        ref: GITHUB_BASE_REF
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: publishToMavenLocal
        build-root-directory: /darkan-core/
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --no-daemon
